### ISSUE TITLE
use full variable syntax for bare variables

### ISSUE THREAD

**Issue by tomkinsc** [dnanexus/dx-streaming-upload#12]
In a [few places](https://github.com/dnanexus-rnd/dx-streaming-upload/blob/365348ed53dcd76086fd885923a1582231dc171d/tasks/main.yml#L153) bare variables are used in this role's playbook. When the playbook is run, Ansible warns that bare variables (ex. `monitored_users`) are deprecated, and should be replaced with jinja2-style variable syntax (ex. `'{{monitored_users}}'`). As of Ansible 2.1.0.0 the role playbooks still work, but they may not in the near future unless the bare variables are wrapped.

**Comment by mlin** [comment]
#14
