### ISSUE TITLE
A couple of beginner's questions

### ISSUE THREAD

**Issue by hartzell** [dnanexus/dx-streaming-upload#21]
1. Is there anything other than the explicit reference to the Ubuntu version  of the `dx-toolkit` tarball in tasks/main.yml that makes this Ubuntu specific?

2. Are the `monitored_directories` being written by the sequencers using the Run Copy Service?

3. I'm interested in running this in support of a MiniSeq.  Any gotcha's I should watch out for?

Thanks

**Comment by hartzell** [comment]
Ping?

**Comment by sclan** [comment]
#1 The dx-toolkit has been changed to the pypi deployment method ( pip3 install dxpy ) so the minimum ubuntu version that the tool supports is (and has been tested via docker) ubuntu 20.04 LTS.

#2 Please consult with your sequencer manual regarding the data transfer method from the sequencer to the filesystem. The streaming upload tool only reads from the monitored folder during its operation. For MiniSeq, the sequencer does utilize Run Copy service based on 
https://knowledge.illumina.com/instrumentation/miniseq/instrumentation-miniseq-reference_material-list/000002021

#3 While we did not test with MiniSeq, the sequencer uses RTAComplete.xml as the completion file which the streaming upload tool does support. The streaming upload tool should run the same way with MiniSeq as the way it works with MiSeq which is supported.
