### ISSUE TITLE
Handling exception raises another exception

### ISSUE THREAD

**Issue by jethror1** [dnanexus/dx-streaming-upload#43]
There's a whitespace in handling of `dxpy.DXError` which raises its own exception when there's an error in uploading a single file from upload_single_file()

**https://github.com/dnanexus/dx-streaming-upload/blob/a14c438db11c77b9c2e8ef5f693fa9b0fead338d/files/incremental_upload.py#L254**

**Comment by emiloslavsky** [comment]
@mhrvol please take a look
