### ISSUE TITLE
Robustness of upload in low internet-bandwidth locale

### ISSUE THREAD

**Issue by tomkinsc** [dnanexus/dx-streaming-upload#6]
Would there be an advantage for monitor_runs.py to [pass](https://github.com/dnanexus-rnd/dx-streaming-upload/blob/master/files/monitor_runs.py#L281) `--max-size` (`-M`) to `incremental_upload.py`, based on a value in the `monitor_runs.config` file? As it is now, if a complete run directory is placed in a path watched by `monitor_runs.py,` a large tarball of the entire run is created. In such cases, will `ua` still upload chunks, or will it attempt to upload the entire large tarball? 

In use cases like ours were connection instability is an issue, we'd prefer to upload many small chunks so dropouts do not interrupt large file transfers.

**Comment by yifei-men** [comment]
UA will split tarball into chunks of size specified [here](https://github.com/dnanexus-rnd/dx-streaming-upload/blob/master/files/dx_sync_directory.py#L452), default = 25Mb.

--max-size specification will not resolve issue related to connection instability, inflight changes on reducing parallelization of upload should, however, alleviate the problem. 

To be closed when parameterization of upload parallelization is merged.

**Comment by yifei-men** [comment]
Addressed by #11
